version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /home/jhoan/portfolio/proxy/certs:/etc/nginx/certs
      - /home/jhoan/vhost.d:/etc/nginx/vhost.d
      - /home/jhoan/portfolio/proxy/html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    restart: always
    environment:
      - DEFAULT_EMAIL=carrerojhoan@gmail.com
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/jhoan/portfolio/proxy/certs:/etc/nginx/certs
      - /home/jhoan/vhost.d:/etc/nginx/vhost.d
      - /home/jhoan/portfolio/proxy/html:/usr/share/nginx/html
      - /home/jhoan/portfolio/proxy/acme:/etc/acme.sh

  # portfolio:
  #   image: jhoacar/portfolio
  #   restart: always
  #   expose:
  #     - "80"
  #   environment:
  #     - VIRTUAL_PORT=80
  #     - VIRTUAL_HOST=prueba.jhoacar.me
  #     - LETSENCRYPT_HOST=prueba.jhoacar.me
  #     - LETSENCRYPT_EMAIL=carrerojhoan@gmail.com
  #   depends_on:
  #     - nginx-proxy
  #     - nginx-proxy-acme


  learning:
    image: jhoacar/learning:v2
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_PORT: 80
      VIRTUAL_HOST: www.learning.jhoacar.me
      LETSENCRYPT_HOST: www.learning.jhoacar.me
      LETSENCRYPT_EMAIL: carrerojhoan@gmail.com

  learning-api:
    image: jhoacar/learning-api:v1
    restart: always
    expose:
      - 8008
    environment:
      DB_CONNECTION: mongodb
      DB_HOST: mongo
      DB_PORT: 27017
      DB_DATABASE: learning
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4-focal
    restart: always
    expose: 
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: learning
    volumes:
      - mongodb:/data/db
      - /home/jhoan/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    expose:
      - 8081
    environment:      
      VIRTUAL_PORT: 8081
      VIRTUAL_HOST: www.mongo.learning.jhoacar.me
      LETSENCRYPT_HOST: www.mongo.learning.jhoacar.me
      LETSENCRYPT_EMAIL: carrerojhoan@gmail.com
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo


#Use MOUNT volume because Mongo need permissions in the system
volumes:
  mongodb:
    external: false 
