ARG PHP_VERSION=7.4
ARG COMPOSER_VERSION=2.0
# ARG ENVIRONMENT_FILE=/home/jhoacar/JHOAN/DBAccess/Interview/backend/.env
# ARG CONFIG_DATABASE=/home/jhoacar/JHOAN/DBAccess/Interview/backend/database.php

FROM composer:${COMPOSER_VERSION}
FROM php:${PHP_VERSION}-apache

RUN apt-get update && \
    apt-get install -y autoconf pkg-config libssl-dev git libzip-dev zlib1g-dev && \
    pecl install mongodb && docker-php-ext-enable mongodb && \
    pecl install xdebug && docker-php-ext-enable xdebug && \
    docker-php-ext-install -j$(nproc) pdo_mysql zip

COPY --from=composer /usr/bin/composer /usr/local/bin/composer

# RUN rm -rf /app

# RUN git clone https://github.com/jhoacar/laravel-mongo-base /app

# RUN composer require -d /app jenssegers/mongodb:*
# RUN php /app/artisan serve --host=0.0.0.0 --port=80 &


WORKDIR /app